categories:
- Data Managers
- Metagenomics
description: Contains data managers that define and populate the bracken_databases
  tool data table.
homepage_url: https://github.com/dfornika/galaxytools/
long_description: |
  While Kraken classifies reads to multiple levels in the taxonomic tree, Bracken allows
  estimation of abundance at a single level using those classifications (e.g. Bracken
  can estimate abundance of species within a sample).
name: data_manager_build_bracken_database
owner: dfornika
remote_repository_url: https://github.com/dfornika/galaxytools/tree/master/data_managers/data_manager_build_bracken_database/
type: unrestricted
