categories:
- Data Managers
description: Contains data managers that define and populate the kma_index tool data table.
homepage_url: https://github.com/dfornika/galaxytools/
long_description: |
  KMA is mapping a method designed to map raw reads directly against redundant databases, in an
  ultra-fast manner using seed and extend. KMA is particulary good at aligning high quality reads
  against highly redundant databases, where unique matches often does not exist. It works for
  long low quality reads as well, such as those from Nanopore. Non-unique matches are resolved using
  the "ConClave" sorting scheme, and a consensus sequence are outputted in addition to other common
  attributes, based on our users demands.
name: data_manager_build_kma_index
owner: dfornika
remote_repository_url: https://github.com/dfornika/galaxytools/tree/master/data_managers/data_manager_build_kma_index/
type: unrestricted
