categories:
- Phylogenetics
description: 'Bioinformatics toolkit for the Nextstrain platform'
long_description: |
  Augur provides ways to perform common bioinformatics tasks through a collection of commands which are designed to be composable into larger processing pipelines. Augur is suitable for use with both relatively small viral genomes, like Zika, as well as much larger bacterial genomes, like tuberculosis.
name: augur
owner: dfornika
remote_repository_url: https://github.com/dfornika/galaxytools/tree/master/tools/augur
homepage_url: https://github.com/nextstrain/augur
type: unrestricted
