categories:
- Data Managers
- Metagenomics
description: Contains data managers that define and populate the mash_sketches
  tool data table.
homepage_url: https://github.com/dfornika/galaxytools/
long_description: |
  Mash extends the MinHash dimensionality-reduction technique to include
  a pairwise mutation distance and P value significance test, enabling the
  efficient clustering and search of massive sequence collections. Mash
  reduces large sequences and sequence sets to small, representative sketches,
  from which global mutation distances can be rapidly estimated.
name: data_manager_build_mash_sketch
owner: dfornika
remote_repository_url: https://github.com/dfornika/galaxytools/tree/master/data_managers/data_manager_build_mash_sketch/
type: unrestricted
